development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://faye-community-friends-cs4900.herokuapp.com/faye"
  secret_token: "94561fe4ad67bcc0b75516cee39b8f9293f940c8d4a9cc556d76e7435e3afe52"
  signature_expiration: 86400 # one day
